# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LuckMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LuckMoneyQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_used', models.BooleanField(default=False)),
                ('luck_money_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lucky_money.LuckMoney')),
            ],
        ),
    ]
